# Based on https://devices.esphome.io/devices/Sonoff-S31

# https://esphome.io/components/substitutions
substitutions:
  cse7766_update_interval: 60s

packages:
  shared_base: !include ../common/device_base.yaml

# https://esphome.io/components/esphome
esphome:
  platform: ESP8266
  board: esp12e

# https://esphome.io/components/logger
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  logs:
    sensor: DEBUG

# https://esphome.io/components/uart
uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

# https://esphome.io/components/time
time:
  - platform: sntp #(required for total_daily_energy)
    timezone: Asia/Tokyo

# https://esphome.io/components/status_led
status_led:
  pin:
    number: GPIO13
    inverted: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Status"

sensor:
    # https://esphome.io/components/sensor/cse7766
  - platform: cse7766
    current:
      name: "Current"
      accuracy_decimals: 2
      filters:
        - throttle_average: ${cse7766_update_interval}
    voltage:
      name: "Voltage"
      accuracy_decimals: 2
      filters:
        - throttle_average: ${cse7766_update_interval}
    power:
      name: "Power"
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: ${cse7766_update_interval}
    energy:
      name: "Energy"
      accuracy_decimals: 2
      filters:
        - throttle: ${cse7766_update_interval}
    apparent_power:
      name: "Apparent Power"
      filters:
        - throttle_average: ${cse7766_update_interval}
    power_factor:
      name: "Power Factor"
      accuracy_decimals: 2
      filters:
        - throttle_average: ${cse7766_update_interval}

    # https://esphome.io/components/sensor/total_daily_energy
  - platform: total_daily_energy
    name: "Daily Energy"
    power_id: my_power
    accuracy_decimals: 2

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON
