# Based on https://devices.esphome.io/devices/Sonoff-S31

# https://esphome.io/components/substitutions
substitutions:
  git_rev: undefined
  cse7766_update_interval: 60s

# https://esphome.io/components/wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

  # ap:
  #   ssid: ${friendly_name} Fallback AP
  #   password: !secret wifi_ap_password

# captive_portal:

# https://esphome.io/components/ota
ota:
  platform: esphome
  port: 3232
  password: !secret ota_password

# https://esphome.io/components/mqtt
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  discovery: true
  discovery_unique_id_generator: mac

# https://esphome.io/components/esphome
esphome:
  platform: ESP8266
  board: esp12e

# https://esphome.io/components/safe_mode
safe_mode:
  disabled: false

# https://esphome.io/components/debug
debug:
  update_interval: 5s

# https://esphome.io/components/logger
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  logs:
    sensor: DEBUG

# https://esphome.io/components/uart
uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

# https://esphome.io/components/time
time:
  - platform: sntp #(required for total_daily_energy)
    timezone: Asia/Tokyo

# https://esphome.io/components/status_led
status_led:
  pin:
    number: GPIO13
    inverted: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Status"

button:
  - platform: safe_mode
    name: "Restart in Safe Mode"
    icon: "mdi:restart-alert"

  - platform: restart
    name: "Restart"
    icon: "mdi:restart"

sensor:
  - platform: debug
    loop_time:
      name: "Loop Time"

    # https://esphome.io/components/sensor/uptime
  - platform: uptime
    update_interval: 60s
    name: Uptime Sensor

    # https://esphome.io/components/sensor/wifi_signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 10s

    # https://esphome.io/components/sensor/cse7766
  - platform: cse7766
    current:
      name: "Current"
      accuracy_decimals: 2
      filters:
        - throttle_average: ${cse7766_update_interval}
    voltage:
      name: "Voltage"
      accuracy_decimals: 2
      filters:
        - throttle_average: ${cse7766_update_interval}
    power:
      name: "Power"
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: ${cse7766_update_interval}
    energy:
      name: "Energy"
      accuracy_decimals: 2
      filters:
        - throttle: ${cse7766_update_interval}
    apparent_power:
      name: "Apparent Power"
      filters:
        - throttle_average: ${cse7766_update_interval}
    power_factor:
      name: "Power Factor"
      accuracy_decimals: 2
      filters:
        - throttle_average: ${cse7766_update_interval}

    # https://esphome.io/components/sensor/total_daily_energy
  - platform: total_daily_energy
    name: "Daily Energy"
    power_id: my_power
    accuracy_decimals: 2

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

text_sensor:
  - platform: debug
    reset_reason:
      name: "Reset Reason"

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

    # https://esphome.io/components/text_sensor/template
  - platform: template
    name: "Git Rev"
    icon: "mdi:source-repository"
    entity_category: "diagnostic"
    lambda: |-
      return {"${git_rev}"};
