esphome:
  name: bedroom-smart-plug-1
  friendly_name: "Bedroom Smart Plug 1"

mqtt:
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: esphome/devices/bedroom_smart_plug_1

packages:
  base: !include { file: .base.yaml }