esphome:
  name: ldk-humidifier
  friendly_name: "LDK Humidifier"

external_components:
  - source:
      type: git
      url: https://github.com/pedorich-n/sharp-smart-humidifier
      path: firmware/esphome_components/

esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP_CONSOLE_USB_CDC: y

light:
  - platform: status_led
    name: "Status"
    output: out_ledc_status

# web_server:
#   port: 80

mqtt:
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: esphome/devices/ldk_humidifier

logger:
  level: INFO

packages:
  shared_base: !include ../common/device_base.yaml

  # prettier-ignore
  led3: !include { file: .led_sensor.yaml, vars: { led: 3, pin: 5, update_interval: 0.3s } } # Mode Auto
  # prettier-ignore
  led4: !include { file: .led_sensor.yaml, vars: { led: 4, pin: 38, update_interval: 0.3s } } # Mode Night
  # prettier-ignore
  led5: !include { file: .led_sensor.yaml, vars: { led: 5, pin: 6, update_interval: 0.3s } } # Mode Eco
  # prettier-ignore
  led2: !include { file: .led_sensor.yaml, vars: { led: 2, pin: 36, update_interval: 0.3s } } # Mode Slow
  # prettier-ignore
  led13: !include { file: .led_sensor.yaml, vars: { led: 13, pin: 39, update_interval: 0.3s } } # Mode Fast
  # prettier-ignore
  led6: !include { file: .led_sensor.yaml, vars: { led: 6, pin: 34, update_interval: 0.3s } } # Mode Ion

  # prettier-ignore
  led14: !include { file: .led_sensor.yaml, vars: { led: 14, pin: 37, update_interval: 1s } } # Bucket Empty
  # prettier-ignore
  led15: !include { file: .led_sensor.yaml, vars: { led: 15, pin: 33, update_interval: 1s } } # Bucket 25%
  # prettier-ignore
  led16: !include { file: .led_sensor.yaml, vars: { led: 16, pin: 35, update_interval: 1s } } # Bucket 50%
  # prettier-ignore
  led9: !include { file: .led_sensor.yaml, vars: { led: 9, pin: 8, update_interval: 1s } } # Bucket Full

output:
  - platform: gpio
    pin: GPIO3
    id: out_sw1
  - platform: gpio
    pin: GPIO40
    id: out_sw2
  - platform: ledc
    id: out_ledc_status
    frequency: "90Hz"
    # Because of `inverted = true`, it's treated as `max_power = 0.2`
    # See: https://github.com/esphome/esphome/blob/654e311/esphome/components/output/float_output.cpp#L36
    min_power: 0.8
    pin:
      number: GPIO15
      inverted: true

button:
  - platform: output
    id: btn_on_off
    name: "On/Off Switch"
    output: out_sw1
    duration: 150ms
    icon: "mdi:power"
  - platform: output
    id: btn_mode
    name: "Mode Switch"
    output: out_sw2
    duration: 150ms
    disabled_by_default: true
    icon: "mdi:fan"

select:
sharp_hv_r75_common:

sharp_hv_r75_operating_mode:
  id: sharp_hv_r75_current_mode
  name: "Operating Mode"
  update_interval: 0.5s
  detections_before_publish: 2
  sensor_mode_auto: led_3_sensor
  sensor_mode_night: led_4_sensor
  sensor_mode_eco: led_5_sensor
  sensor_mode_fan_slow: led_2_sensor
  sensor_mode_fan_fast: led_13_sensor
  sensor_ion: led_6_sensor

sharp_hv_r75_operating_mode_select:
  id: sharp_hv_r75_operating_mode_selector
  name: "Operating Mode Select"

sharp_hv_r75_operating_mode_control:
  update_interval: 2s
  sensor_operating_mode: sharp_hv_r75_current_mode
  select_operating_mode: sharp_hv_r75_operating_mode_selector
  button_on_off: btn_on_off
  button_mode: btn_mode

sharp_hv_r75_water_level:
  name: "Water Level"
  update_interval: 1s
  detections_before_publish: 2
  sensor_bucket_empty: led_14_sensor
  sensor_bucket_low: led_15_sensor
  sensor_bucket_mid: led_16_sensor
  sensor_bucket_full: led_9_sensor
